### ISSUE TITLE
Can't edit fallback action button once created and other problems. 

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#567] opened 2019-02-10 15:44 UTC
On the Agent screen and creating a new fallback action from default, after puting in once response. It says:
"Please add at least one response." It should say "Please add, one more response." When clicking save, it goes to the agent screen where the fallback action that has only 1 response can be selected, but not edited to put another response in.

**Comment by wrathagom** [comment] 2019-02-10 15:45
screenshots, console errors, was this a new agent?

**Comment by wrathagom** [comment] 2019-02-10 15:46
also only one response is required not two, are you sure you pressed enter to actually submit the response?

**Comment by RussellSPG** [comment] 2019-02-10 15:47
Error:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://api.github.com/_private/browser/stats’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).[Learn More]
Failed to update content 
<div class="timeline-comment-wrapper… mt-0 js-socket-channel" data-gid="MDU6SXNzdWU0MDg1NDc2MjU=" data-url="/_render_node/MDU6SXNzdWU0MDg1NDc2MjU=/issues/body" data-channel="issue:408547625">
 Error: "element had interactions"

    updateContent updatable-content.js:37 

updatable-content.js:43:6
Failed to update content 
<div class="timeline-comment-wrapper… mt-0 js-socket-channel" data-gid="MDU6SXNzdWU0MDg1NDc2MjU=" data-url="/_render_node/MDU6SXNzdWU0MDg1NDc2MjU=/issues/body" data-channel="issue:408547625">
 Error: "element had interactions"

    updateContent updatable-content.js:37 
```

**Comment by RussellSPG** [comment] 2019-02-10 15:48
> 
> 
> also only one response is required not two, are you sure you pressed enter to actually submit the response?

Yes, so I'm saying after puting one response in it should say, "please enter 1 more response." And it shouldn't be allowed to save and return back to the Agent screen with only 1 response.

**Comment by RussellSPG** [comment] 2019-02-10 15:48
> 
> 
> also only one response is required not two, are you sure you pressed enter to actually submit the response?

yes I pressed Enter

**Comment by RussellSPG** [comment] 2019-02-10 15:55
Screenshot
![image](https://user-images.githubusercontent.com/42249324/52535949-2e85ff80-2d09-11e9-9c1d-2a050cf5296f.png)
Point is, after adding another response hitting save, the error message doesn't update.

**Comment by wrathagom** [comment] 2019-02-10 15:57
that is a duplicate of an issue you already created

**Comment by wrathagom** [comment] 2019-02-10 15:58
one response is perfectly acceptable. It's two sayings are required for an action.

**Closed** 2019-02-10 16:03 UTC
