### ISSUE TITLE
default fallback action disappears when saving.

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#593] opened 2019-02-23 19:10 UTC
Please describe the issue you are having here and answer the question below.

When creating a new agent, placing in the Name, and Description and clicking the Save icon, the "default fallback action" selection in drop-down doesn't exist. Only "+ new action" is seen. However, before clicking the save icon when in creating agent screen, it is there.

When clicking the save, and check mark appears, you have to click Agent again and the "default fallback action" is there again. So just a minor visual glitch. 

![image](https://user-images.githubusercontent.com/42249324/53290714-0a4d0880-3776-11e9-9260-78f348a096d8.png)

No errors on console detected.

- Did you download a release or pull from Master? Which release?
0.21
- What operating system are you running?
Windows 10 Pro
- Are you running locally or in the cloud?
locally
- Which browser are you using?
Firefox, but tried on edge, and chrome as well

----

**Comment by wrathagom** [comment] 2019-02-26 03:19
It looks like the default fallback action may not have been craeted when the agent was? Or was this an import?

If you can get it to do it again then check for browser console errors, otherwise we'll close the issue until you see it pop back up again.

**Comment by RussellSPG** [comment] 2019-03-01 20:57
Same issue on new version v0.21.1

![image](https://user-images.githubusercontent.com/42249324/53665828-8940b600-3c3a-11e9-9e22-dc2a051cc724.png)

```
TypeError: o is not a function[Learn More] vendors~main.162b6a815684c830881f.chunk.js:18:12099

    unsubscribe http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:18 _onMessage http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:18 _onMessage http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:18 _onMessage http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:18 onmessage http://localhost:3000/vendors~main.162b6a815684c830881f.chunk.js:18 
```

**Comment by wrathagom** [comment] 2019-03-01 21:07
can you describe what led up to this? Did you just recently do a `docker-compose up` or was this instance already running?

is this an import or a fresh create? Why is the agent already trained?

**Comment by RussellSPG** [comment] 2019-03-01 21:15
Yes, updated latest from repo:
 ran docker-compose pull
 git pull, verified new tag created 21.1
docker-compose up -d
docker-compose
No errors getting it up and everything started normally. Yes its completely fresh, as before thats when I'd get the error, and its not trained, just clicked the save following my script

**Comment by wrathagom** [comment] 2019-03-01 21:25
@dcalvom I can reproduce this, but didn't understand it at first. When creating a new agent the default fallback action is shown in the dropdown, but when you click save it disappears from the list.

**Comment by dcalvom** [comment] 2019-03-11 23:01
Closed by https://github.com/samtecspg/articulate/commit/a943c3d74105e5b984e419401e93917d34402b59

**Closed by dcalvom** 2019-03-11 23:01 UTC
