### ISSUE TITLE
Deleting keyword causes page to crash

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#612] opened 2019-03-01 22:26 UTC
When deleting a keyword, the page will crash with this:

![image](https://user-images.githubusercontent.com/42249324/53669821-7633e300-3c46-11e9-9ddd-f6b8db64c495.png)
No error message just this:
```window.controllers/Controllers is deprecated. Do not use it for UA detection.```

However, the keyword does delete when refreshing the page.

I have tried:
-Closing other web applications, only running articulate
-Re-upping the containers/restarting articulate
-Restarting docker, downing docker-compose before.
-Tried testing on edge browser, same result.

- Did you download a release or pull from Master? Which release?
v0.21.1
- What operating system are you running?
10 Pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
Firefox. 

----

**Comment by wrathagom** [comment] 2019-03-01 22:29
What is the URL it is trying to access?

Did the keyword have values? modifiers? was it in use by any actions?

I can't reproduce this as of right now.

**Comment by RussellSPG** [comment] 2019-03-01 22:32
url: http://localhost:3000/agent/7/keywords
Keyword did have values, a b according to my script. Was not used with any actions, just testing functionality when creating ones.

**Comment by wrathagom** [comment] 2019-05-15 13:58
Fixed on master

**Closed by wrathagom** 2019-05-15 13:58 UTC
