### ISSUE TITLE
Training chatbot with JSON file

### ISSUE THREAD

**Issue by ngcgolf11** [samtecspg/articulate#1048] opened 2020-05-07 04:53 UTC
Hi Articulate Team,

Can we train Articulate from any JSON file which we get after convert the PDF to JSON. 
we only want to build a system where chatbot can give answer from book and also anyone can search from that book chatbot can give its answer 

please help me how we can do that the number of books is 50. Thanks in advance.

Regards:
Manoj Kumar

**Comment by ngcgolf11** [comment] 2020-05-07 09:58
I have a history book in which there are many chapters I want chatbot will give students answer if they ask any question from chatbot that answer in that book. 
Please provide me a solution I am working on this project for free

**Comment by wrathagom** [comment] 2020-05-07 12:24
If you have a JSON file of questions and answers you could use the API to load them into Articulate as sayings, actions, and responses.

I would need a sample of the JSON to say much more.

**Comment by ngcgolf11** [comment] 2020-05-10 11:41
how we can train with pdf if we convert the pdf into json we can do that or not

**Comment by dcalvom** [comment] 2020-05-10 21:22
Hi there!

What is your goal? To let the agent answer questions from the pdf content?

**Comment by wrathagom** [comment] 2020-05-12 15:42
Somewhat a duplicate of #1032 You can't train Articulate from JSON, PDF, or MySQL. To train it you need to use the UI or API to provide labeled sayings. Each saying can be tagged with one or more actions. Actions, then can call a webhook to fetch data.

If you have a JSON of question/answers. Or can pull questions/answers from a PDF, then you could write a custom script that uses the API to add all of those into Articulate, but you would need to have the questions and answers in a JSON/CSV/etc file first.

**Comment by wrathagom** [comment] 2020-05-12 15:43
Maybe this will help https://blog.spg.ai/build-a-faq-chatbot-with-articulate-fd9ff8dc1235

**Closed by wrathagom** 2020-05-12 15:42 UTC
Labels: question
