### ISSUE TITLE
Can't create an agent, please help.

### ISSUE THREAD

**Issue by macasas** [samtecspg/articulate#176] opened 2018-04-28 04:28 UTC
I ran your installation. I get the webpage, the buttons take me to pages, but it does not create an agent, so cannot create anything else. This functionality does not need 8Gb, so what am I missing?

**Comment by Johnz86** [comment] 2018-04-28 10:06
Most probable cause is that your webpage is not communicating with API docker container. You can check this, in browser dev tools and in network tab you will see that the page fails to load swagger.json file from the API container. You need to have properly configured ```.env``` file in your project root, before you start ```docker-compose up```.

**Comment by wrathagom** [comment] 2018-04-28 11:48
@macasas sorry that your default install isn't working for you, we're more than willing to help you get it running if you are willing to work with us. 

What operating system are you running?
Did you download a release or pull from master?
Are there any errors in the docker-compose logs?
Are there any errors in the webpage console?
What webpage are you going to that is dead?

@Johnz86 running locally on Unix or Mac there are no configuration changes necessary for most people. Or has your experience with it shown you otherwise?

**Comment by Johnz86** [comment] 2018-04-28 15:04
@wrathagom  I noticed this behaviour first, when I tried local setup on my Windows 7 and docker-machine. The UI started and clicking on the create button did nothing. I noticed the errors in browser dev tools network tab. After some investigation I did setup a proper .env file and everything worked. Then I tried do similar stuff in AWS cloud VM. I allowed UI port for docker container and forgot to allow API docker container port for public acess, I got the same UI behaviour. After allowing the API container port for public access it worked like a charm.

**Comment by macasas** [comment] 2018-04-28 15:38
On 28 April 2018 at 13:48:31, Caleb M. Keller (notifications@github.com)
wrote:

@macasas <https://github.com/macasas> sorry that your default install isn't
working for you, we're more than willing to help you get it running if you
are willing to work with us.

What operating system are you running?

OSX 10.12

Did you download a release or pull from master?

Followed instructions on your github page

Are there any errors in the docker-compose logs?

Just installed Docker, just to install your application, no idea where any
logs are, cannot see anything in the menus.


Are there any errors in the webpage console?

Failed to load swagger.json, @Johnz86 was on the money, despite being on
Windows.

[Log] [HMR] connected


What webpage are you going to that is dead?

It loads the page, the button highlights, but it just doesn’t do anything
when trying to create an agent.


@Johnz86 <https://github.com/Johnz86> running locally on Unix or Mac there
are no configuration changes necessary for most people. Or has your
experience with it shown you otherwise?

Looks like I’m not most people, because I’m on Mac and its showing Johnz86
swagger.json error


Thanks


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/samtecspg/articulate/issues/176#issuecomment-385169194>,
or mute the thread

**Comment by wrathagom** [comment] 2018-04-28 15:42
@macasas Can you tell me what the output of `docker ps -a` is?

**Comment by macasas** [comment] 2018-04-28 15:46
daves-air:~ dave$ docker ps -a

CONTAINER ID        IMAGE                                 COMMAND
        CREATED             STATUS                    PORTS
              NAMES

b31f00b47e56        samtecspg/articulate-ui:repo-head     "yarn start"
        18 hours ago        Up 18 hours               0.0.0.0:3000->3000/tcp
            articulate-071_ui_1

7c1fc1506926        samtecspg/articulate-rasa:repo-head   "./entrypoint.sh
sta…"   18 hours ago        Up 18 hours               0.0.0.0:5000->5000/tcp
            articulate-071_rasa_1

7c8022ca6cfd        samtecspg/articulate-api:repo-head    "node start.js"
        18 hours ago        Up 18 hours (unhealthy)   7500/tcp,
0.0.0.0:8000->8000/tcp
  articulate-071_api_1

696aabd72cc3        samtecspg/duckling:0.1.0.0            "/bin/sh -c
'stack e…"   18 hours ago        Up 18 hours
0.0.0.0:8500->8000/tcp
            articulate-071_duckling_1

07efee555cce        redis:4.0.6-alpine
"docker-entrypoint.s…"   18 hours ago        Up 18 hours
0.0.0.0:6379->6379/tcp             articulate-071_redis_1


On 28 April 2018 at 17:42:20, Caleb M. Keller (notifications@github.com)
wrote:

docker ps -a

**Comment by macasas** [comment] 2018-04-28 16:25
And doing a search finds nothing for swagger.json or even swagger

I don’t know where this file is supposed to be,

all I can find is a swagger.yml file


On 28 April 2018 at 18:23:47, David MacDougall (davemacac@gmail.com) wrote:

Failed to load resource: net::ERR_EMPTY_RESPONSE
:8000/swagger.json

In Chrome I get the same message, and then noticed it is saying 8000, not
3000
Is that the issue?

On 28 April 2018 at 18:22:00, David MacDougall (davemacac@gmail.com) wrote:

 http://localhost:3000/documentation Uuups we didn't found that!
and this message would be better as "Ooops, we didn’t find that!"

yes, I am using localhost:3000



On 28 April 2018 at 18:19:34, Caleb M. Keller (notifications@github.com)
wrote:

@Johnz86 <https://github.com/Johnz86> I remember your issue, our support
for docker-machine was non-existent. Glad you pointed it out and got your
install running. I've opened #178
<https://github.com/samtecspg/articulate/issues/178> and #179
<https://github.com/samtecspg/articulate/issues/179> to try and make it
more obvious when things aren't working right specifically with the API and
we'll link to docs for common troubleshooting problems. This one is
interesting because he's essentially running it the way we run it, but
having your kind of problems. Suggests something is different about the
network setup.

@macasas <https://github.com/macasas> everything is running, so that is a
good sign.

when you try to go to http://localhost:3000/documentation do you get
anywhere? When accessing the UI are you going to localhost or some local ip
like 192.168.111.1?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/samtecspg/articulate/issues/176#issuecomment-385187672>,
or mute the thread

**Comment by wrathagom** [comment] 2018-04-28 16:35
I had the documentation address wrong, can you access http://localhost:8000/documentation?

It's interesting that the error is just `Failed to load resource: net::ERR_EMPTY_RESPONSE
:8000/swagger.json` with no host before it. We're getting closer to the root problem.

**Comment by wrathagom** [comment] 2018-04-28 17:00
@macasas I know what the problem is. I am going to try and tip up instructions on how to unwind it. Give me a little bit to boil it down.

**Comment by wrathagom** [comment] 2018-04-28 17:14
@macasas there is a problem in the source code file that you downloaded. When we made the release, we didn't update it to point to the 0.7.1 tag. It instead points to master, but we're making port changes in master. That's where the problem is originating.

So first let's clean up the old install. From a terminal in the `articulate-0.7.1` folder enter the following:

```
docker-compose down
```

Once that is finished delete the entire `articulate-0.7.1` folder and download the file from [this page](https://github.com/samtecspg/articulate/releases/tag/v0.7.1) labeled `articulate-v0.7.1.zip`. It's essential to download that one as opposed to the source code files since the source code files contain the error.

<img width="984" alt="2018-04-28_13-08-22" src="https://user-images.githubusercontent.com/1779894/39399092-b4a6de1a-4ae5-11e8-86b4-2008f4927981.png">

Once you've got that downloaded, you can do the `docker-compose up` from the unzipped folder.

**Comment by macasas** [comment] 2018-04-28 19:16
Okay thanks, I’ve done that and it is now allowing me to add an agent, a
domain and an intent.

Can you tell me, what and where has it installed 10Gb of stuff, because it
 has used up all my free space, the first installation used 8Gb, then
deleting and reinstalling has used up an additional 2Gb.  The articulate
folder is not even close to this, so where is everything?



On 28 April 2018 at 19:14:19, Caleb M. Keller (notifications@github.com)
wrote:

@macasas <https://github.com/macasas> there is a problem in the source code
file that you downloaded. When we made the release, we didn't update it to
point to the 0.7.1 tag. It instead points to master, but we're making port
changes in master. That's where the problem is originating.

So first let's clean up the old install. From a terminal in the
articulate-0.7.1 folder enter the following:

docker-compose down

Once that is finished delete the entire articulate-0.7.1 folder and
download the file from this page
<https://github.com/samtecspg/articulate/releases/tag/v0.7.1> labeled
articulate-v0.7.1.zip. It's essential to download that one as opposed to
the source code files since the source code files contain the error.

[image: 2018-04-28_13-08-22]
<https://user-images.githubusercontent.com/1779894/39399092-b4a6de1a-4ae5-11e8-86b4-2008f4927981.png>

Once you've got that downloaded, you can do the docker-compose up from the
unzipped folder.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/samtecspg/articulate/issues/176#issuecomment-385191600>,
or mute the thread

**Comment by wrathagom** [comment] 2018-04-28 19:26
We were curious where the 8Gb was coming from as the actual install is more like 2.5Gb, but if you're looking at the size on disk, then that is a Docker artifact as it reserves a chunk of space by creating a file to store its data in.

Here's the issue with Docker if you're interested: https://github.com/docker/for-mac/issues/371

If you're finished playing with Articulate and just want to get rid of everything the easiest way to do that is to reset all your Docker data or remove Docker entirely.

<img width="500" alt="2018-04-28_15-24-03" src="https://user-images.githubusercontent.com/1779894/39400114-3cb19cac-4af8-11e8-8c8b-c1e17c1cfcdd.png">

@macasas we will soon be offering a free hosted trial, if we had had that today would you have chosen it over installing Docker and trying locally?

**Comment by macasas** [comment] 2018-04-29 09:51
When I Reset, I gain back 16Gb of hard drive space.

When I restart Docker the qcow2 grows to 1.5Gb and then when I run docker
up again I lose a further 10Gb, from a user experience perspective, the
process is very poor because to run your page I have to re-download
everything via docker up, plus lose a load of disk space, so am I doing the
right thing, is there a different “docker start” to start the app after
“docker up” installs it, or must I run “docker up each time i want to start
the localhost server?

Free trials either shut off after 30 days, which is a pointless exercise or
they are use-restrictive while free, which gives me a better chance to
learn what it does and how I can use it in a project. I’m a freelancer, so
I don’t have all day to play with free trials, so a 30 day free trial is
probably only accessed 4 times when freetime allows.

On the other hand, I prefer if I can take it offline because I travel a
lot, and cannot alway connect, so having it on my laptop is a big help, and
I can play with it during a flight, for example.




On 28 April 2018 at 21:26:09, Caleb M. Keller (notifications@github.com)
wrote:

We were curious where the 8Gb was coming from as the actual install is more
like 2.5Gb, but if you're looking at the size on disk, then that is a
Docker artifact as it reserves a chunk of space by creating a file to store
its data in.

Here's the issue with Docker if you're interested: docker/for-mac#371
<https://github.com/docker/for-mac/issues/371>

If you're finished playing with Articulate and just want to get rid of
everything the easiest way to do that is to reset all your Docker data or
remove Docker entirely.

[image: 2018-04-28_15-24-03]
<https://user-images.githubusercontent.com/1779894/39400114-3cb19cac-4af8-11e8-8c8b-c1e17c1cfcdd.png>

@macasas <https://github.com/macasas> we will soon be offering a free
hosted trial, if we had had that today would you have chosen it over
installing Docker and trying locally?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/samtecspg/articulate/issues/176#issuecomment-385200095>,
or mute the thread

**Comment by wrathagom** [comment] 2018-04-29 12:55
@macasas several questions rolled into one there.

- Whenever you are finished testing locally you can `Ctrl+C` to stop the application running in the terminal. Once that is done you can type `docker-compose down`. That will stop everything, but not free up the disk space.
- The next time you run, so long as you have not reset the Docker data `docker-compose up` should not have to re-download anything, it should just create new containers 
- Keep in mind that nothing will shrink the size of the qcow2 file, it only grows. Until you reset the Docker data, but doing that will cause everything to re-download the next time it starts up.

One thing that may help is to limit the size of the qcow file, but on my computer, the smallest option is 16Gb which is still quite large:

<img width="509" alt="2018-04-29_08-53-47" src="https://user-images.githubusercontent.com/1779894/39406820-ec9650a8-4b8a-11e8-90e4-4ece77a49e92.png">

**Comment by macasas** [comment] 2018-04-29 12:58
I’m new to Docker, and to be honest the cost far outweighs the benefits of
using your app.  Sorry, but I’ve switched it all off.


On 29 April 2018 at 14:55:13, Caleb M. Keller (notifications@github.com)
wrote:

@macasas <https://github.com/macasas> several questions rolled into one
there.

   - Whenever you are finished testing locally you can Ctrl+C to stop the
   application running in the terminal. Once that is done you can type
docker-compose
   down. That will stop everything, but not free up the disk space.
   - The next time you run, so long as you have not reset the Docker
data docker-compose
   up should not have to re-download anything, it should just create new
   containers
   - Keep in mind that nothing will shrink the size of the qcow2 file, it
   only grows. Until you reset the Docker data, but doing that will cause
   everything to re-download the next time it starts up.

One thing that may help is to limit the size of the qcow file, but on my
computer, the smallest option is 16Gb which is still quite large:

[image: 2018-04-29_08-53-47]
<https://user-images.githubusercontent.com/1779894/39406820-ec9650a8-4b8a-11e8-90e4-4ece77a49e92.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/samtecspg/articulate/issues/176#issuecomment-385249554>,
or mute the thread

**Comment by wrathagom** [comment] 2018-04-29 13:04
No worries here, Docker is probably the single most useful tool that I've added to my developer toolkit in some years, but it comes with a few prices.

Let me know if you'd like for us to set up a cloud instance for you to experiment with. We'll leave it running almost indefinitely so long as it is getting some use as feedback is valuable at the stage we are in.

Otherwise, I will close the issue.

**Comment by macasas** [comment] 2018-04-29 13:08
Yes, I would like to try your cloud instance, where should I go to do
that?  Then close this issue, thanks for your help.


On 29 April 2018 at 15:04:41, Caleb M. Keller (notifications@github.com)
wrote:

No worries here, Docker is probably the single most useful tool that I've
added to my developer toolkit in some years, but it comes with a few prices.

Let me know if you'd like for us to set up a cloud instance for you to
experiment with. We'll leave it running almost indefinitely so long as it
is getting some use as feedback is valuable at the stage we are in.

Otherwise, I will close the issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/samtecspg/articulate/issues/176#issuecomment-385250110>,
or mute the thread

**Comment by wrathagom** [comment] 2018-04-30 14:36
@macasas we don't have the self-service piece of this fully operational. I'll get your instance set up today or tomorrow and send you an e-mail.

Do you mind e-mailing me so that I have your e-mail address?

We'll do the rest via e-mail.

**Closed by wrathagom** 2018-04-30 14:36 UTC
Labels: bug
