### ISSUE TITLE
articulate doesn't run

### ISSUE THREAD

**Issue by aermike** [samtecspg/articulate#945] opened 2019-10-18 09:40 UTC
### Issues
> *If you're having trouble with Articulate we definitely want to help you. If you can provide a little bit of information it will make our troubleshooting job easier.*
api_1_3314ee1eb06f | 2019/10/18 09:31:12 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
api_1_3314ee1eb06f | 2019/10/18 09:31:13 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
api_1_3314ee1eb06f | 2019/10/18 09:31:14 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s
api_1_3314ee1eb06f | 2019/10/18 09:31:15 Problem with request: Get http://elasticsearch:9200: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host. Sleeping 1s

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?

Latest commit
749fc03

- What operating system are you running?
CentOS 7 VM 4 vCore 8192MBRAM 100GB hdd
- Are you running locally or in the cloud?
Locally
- Which browser are you using?
Firefox
----

### Feature Request
> *If you've got a feature request we want to hear it*

Please desribe the feature you would like us to add.

If possible provide the use case for the feature and how you would use it.

**Comment by wrathagom** [comment] 2019-10-21 19:37
This looks like normal operation. How long did you wait? Elasticsearch can take several minutes to startup.

**Comment by aermike** [comment] 2019-10-22 05:22
I wait about 2 minutes
How long should I wait?

**Comment by wrathagom** [comment] 2019-10-22 22:38
can you run it again and wait at least 5 minutes. If it still doesn't start after that can you paste the output of `docker-compose logs elasticsearch`

**Comment by aermike** [comment] 2019-10-23 05:53
It works, but graafic interface is loading. I wait about 15 minute

**Comment by wrathagom** [comment] 2019-10-23 09:58
Well then it's not really working. What about the output of `docker-compose logs elasticsearch`?

**Comment by aermike** [comment] 2019-10-23 19:06
it's ok 
he's come down

**Comment by wrathagom** [comment] 2019-10-23 23:02
?

**Comment by aermike** [comment] 2019-10-24 05:34
logs are ok.
elasticsearch started, but web interface doesn't

**Comment by wrathagom** [comment] 2019-10-24 12:14
I want to see the logs. Also the API logs.

```
docker-compose logs api elasticsearch
```

**Comment by aermike** [comment] 2019-10-25 06:43
hi
here is the log
https://pastebin.com/7zNf9avW and errors
https://pastebin.com/7hSgmRM2
here is history of commands in console and screen
 articulate]# history
    1  yum install -y screen git mc
    2  scren
    3  screen
    4  yum install -y sudo
    5  screen -r
    6  history
    7  screen -r
    8  docker-compose logs api elasticsearch
    9  screen -r
   10  docker-compose logs api elasticsearch
   11  cd /opt/articulate/
   12  docker-compose logs api elasticsearch
   13  screen -r
   14  docker-compose logs api elasticsearch
   15  screen -r
   16  docker-compose logs api elasticsearch
   17  docker-compose logs api
   18  docker-compose logs api elasticsearch
   19  systemctl stop firewalld
   20  docker-compose logs api elasticsearch
   21  cd /opt/articulate/
   22  docker-compose logs api elasticsearch
   23  clear
   24  docker-compose logs api elasticsearch
   25  platform articulate]# docker-compose logs api elasticsearch
latform articulate]# history
    1  sudo yum check-update
    2  curl -fsSL https://get.docker.com/ | sh
    3    sudo usermod -aG docker your-user
    4  sudo usermod -aG docker root
    5  sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    6  sudo chmod +x /usr/local/bin/docker-compose
    7  sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    8  docker-compose -v
    9  cd /opt/
   10  yum install -y unzip
   11  git clone https://github.com/samtecspg/articulate.git
   12  cd articulate/
   13  docker-compose up
   14  systemctl start docker
   15  docker-compose up

Errors
nginx_1          | 2019/10/25 06:42:31 [error] 6#6: *156 connect() failed (111: Connection refused) while connecting to upstream, client: 10.33.0.150, server: localhost, request: "GET /api/ HTTP/1.1", upstream: "http://172.18.0.8:7500/", host: "10.33.0.42:8080"
nginx_1          | 10.33.0.150 - - [25/Oct/2019:06:42:31 +0000] "GET /api/ HTTP/1.1" 502 158 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0" "-"

**Comment by dcalvom** [comment] 2019-10-25 06:57
Hi, @aermike, I saw you are running master. Have you been able to run Articulate before?

**Comment by aermike** [comment] 2019-10-25 08:14
hi
No

**Comment by aermike** [comment] 2019-10-25 11:04
nginx_1          | 2019/10/25 11:03:08 [error] 6#6: *92 connect() failed (113: Host is unreachable) while connecting to upstream, client: 10.33.0.150, server: localhost, request: "GET /api/ HTTP/1.1", upstream: "http://172.18.0.8:7500/", host: "10.33.0.42:8080"
nginx_1          | 10.33.0.150 - - [25/Oct/2019:11:03:08 +0000] "GET /api/ HTTP/1.1" 502 158 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0" "-"
nginx_1          | 2019/10/25 11:03:16 [error] 6#6: *94 connect() failed (113: Host is unreachable) while connecting to upstream, client: 10.33.0.150, server: localhost, request: "GET /api/ HTTP/1.1", upstream: "http://172.18.0.8:7500/", host: "10.33.0.42:8080"
nginx_1          | 10.33.0.150 - - [25/Oct/2019:11:03:16 +0000] "GET /api/ HTTP/1.1" 502 158 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0" "-"
nginx_1          | 2019/10/25 11:03:24 [error] 6#6: *96 connect() failed (113: Host is unreachable) while connecting to upstream, client: 10.33.0.150, server: localhost, request: "GET /api/ HTTP/1.1", upstream: "http://172.18.0.8:7500/", host: "10.33.0.42:8080"
nginx_1          | 10.33.0.150 - - [25/Oct/2019:11:03:24 +0000] "GET /api/ HTTP/1.1" 502 158 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0" "-"

**Comment by aermike** [comment] 2019-10-28 11:02
any news?

**Comment by wrathagom** [comment] 2019-10-28 13:47
Here's the actually error:

```
elasticsearch_1  | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch_1  |      at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:385) ~[?:?]
elasticsearch_1  |      at java.nio.file.Files.createDirectory(Files.java:689) ~[?:?]
elasticsearch_1  |      at java.nio.file.Files.createAndCheckIsDirectory(Files.java:796) ~[?:?]
elasticsearch_1  |      at java.nio.file.Files.createDirectories(Files.java:782) ~[?:?]
elasticsearch_1  |      at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:270) ~[elasticsearch-
```

this is a duplicate of #659, Here's my answer from that post:

the access denied error for Elasticsearch just means that the user you're running Docker with isn't UID 1000

You probably could've solved this on Ubuntu with sudo chown -R 1000:1000 local-storage/elasticsearch

**Comment by aermike** [comment] 2019-10-28 14:16
Hi
It works with
sudo chown -R 1000:1000 local-storage/elasticsearch
Thank you

**Closed** 2019-10-28 14:17 UTC
