### ISSUE TITLE
Unable to deploy Articulate in Windows. "HNS failed with error : The parameter is incorrect"

### ISSUE THREAD

**Issue by amritapcs** [samtecspg/articulate#249] opened 2018-06-17 07:13 UTC
I am trying to install on google cloud but getting error for the command "docker-compose up" as "alpha-nlu-network" parameter is not correct. HNS service is not started due to invalid parameter. As per the documentation i have changed the localhost with the public vm ip. I have done the changes for Api_url, Swagger_host and docker_instance. Please advice.

**Comment by dcalvom** [comment] 2018-06-17 07:56
Hi @amritapcs would you mind to answers this questions please to help you out

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release?
- What operating system are you running?
- Are you running locally or in the cloud?
- Which browser are you using?

**Comment by amritapcs** [comment] 2018-06-17 13:41
Pl see my revert below in red .Appreciate your quick revert.

Regards
Amrita Anand

**Comment by dcalvom** [comment] 2018-06-17 13:46
Thanks for your answers. So are you running docker on windows? Right?

**Comment by amritapcs** [comment] 2018-06-17 13:53
Yes.

Regards
Amrita Anand

**Comment by dcalvom** [comment] 2018-06-17 13:58
By looking on docker issues it seems it could be related with an issue. Could you check if you are able to update your docker?

**Comment by dcalvom** [comment] 2018-06-17 18:37
By the way, Master branch is our working space, so it isn't stable. We recommend you to use our [latest release](https://github.com/samtecspg/articulate/releases/tag/v0.9.4) and follow the [cloud installation instructions](https://samtecspg.github.io/articulate/getting_started/cloud-installation)

**Comment by amritapcs** [comment] 2018-06-18 02:37
Daniel,

I tried as suggested still getting error after running docker-compose up.



Regards
Amrita Anand

**Comment by wrathagom** [comment] 2018-06-18 02:47
@amritapcs can I get the exact error message. Copy paste/screenshot?

**Comment by amritapcs** [comment] 2018-06-18 03:04
Pl find the attached error as well as revised docker-compose.yml file and
env file


Regards
Amrita Anand

**Comment by dcalvom** [comment] 2018-06-18 03:08
@amritapcs Given that you are directly answering the emails from GitHub we aren't able to see the files you attached. Could you please attach them by firstly accessing into this link https://github.com/samtecspg/articulate/issues/249 and then attaching the files in a new comment

**Comment by amritapcs** [comment] 2018-06-18 03:18
Pl check the attached file.

[articulate_error.docx](https://github.com/samtecspg/articulate/files/2109790/articulate_error.docx)

**Comment by dcalvom** [comment] 2018-06-18 17:30
After reviewing your document I confirmed this is totally related with your docker set up in your windows machine.

You can get information about your particular error here:
https://github.com/docker/compose/issues/4024
https://github.com/docker/for-win/issues/598
https://github.com/docker/compose/issues/4149

The most common fix seems to be this [one](https://stackoverflow.com/questions/45394360/hns-failed-with-error-the-parameter-is-incorrect), taked from stackoverflow:

This is a known limitation. At present windows only supports one NAT network. Removing Netnat by invoke Remove-Netnat is not supported.

Run this in powesrhell.

`Get-NetNat | Remove-NetNat`

**Comment by wrathagom** [comment] 2018-06-19 01:53
@amritapcs let us know if that solves your issue. If not, do you have the option of creating a linux VM on GCS?

**Comment by amritapcs** [comment] 2018-06-19 10:50
Hi,

Thanks for you suggestion.
I have successfully install articulate on ubuntu VM. Now I want to check to
the code and want to customize as per my requirement. Can you please guide
me where I will get those file.

Thanks
Amrita

Regards
Amrita Anand

**Comment by wrathagom** [comment] 2018-06-19 11:49
Our défaut releases don't include the code, just a compose file and some config files.

If you want to the code you'll want to `git clone https://github.com/samtecspg/articulate.git`and you will have all of the source files!

Let us know if you run into any other problems.

**Comment by amritapcs** [comment] 2018-06-19 12:12
Hi,

can we add a login page.

Thanks
Amrita

Regards
Amrita Anand

**Comment by milutz** [comment] 2018-06-19 12:44
Amrita,

  For a process to fronend articulate with a login, please see the link on Issue#162 (that also links to issue 22 which is about the (future) direct implimention of a login interface)

**Comment by milutz** [comment] 2018-06-19 12:45
@amritapcs (forgot to paste link) I mean this issue https://github.com/samtecspg/articulate/issues/162

**Comment by dcalvom** [comment] 2018-06-19 15:30
Based on @amritapcs comment `I have successfully install articulate on ubuntu VM`

We can close this issue.

**Closed by dcalvom** 2018-06-19 15:30 UTC
Labels: bug
