### ISSUE TITLE
Creating an action in API needs to verify webhook and post format exist if being used

### ISSUE THREAD

**Issue by cjhurst** [samtecspg/articulate#602] opened 2019-02-26 13:58 UTC
On samson-dev, I was attempting to use the api to upload some actions for assignment. I was having trouble because I copied the example for the post in the swagger docs and that had `"useWebhook":true, "postFormat":true`. If so, it will upload them, and it will show in the assignment dialogue, but the name won't show up when you go to edit them. It says "no name".

**Comment by cjhurst** [comment] 2019-02-26 13:59
@wrathagom

**Comment by wrathagom** [comment] 2019-05-15 13:55
@dcalvom I can reproduce this one. I am assuming it is because the web hook and post format don't exist so when they are loaded there is an error:

We shouldn't let the user create an acton with useWebhook: true or postFormat: true without verifying that they have been created first.

**Comment by dcalvom** [comment] 2019-06-05 16:28
Closed by https://github.com/samtecspg/articulate/commit/2bd46790ca233c5465047877d0399557f9523c0e

**Closed by dcalvom** 2019-06-05 16:28 UTC
Labels: api, bug
