### ISSUE TITLE
Dynamic buttons from webhook requests

### ISSUE THREAD

**Issue by Ravenous** [samtecspg/articulate#964] opened 2019-11-27 18:19 UTC
### Feature Request
Create dynamic buttons and response values from webhook requests for quick response

![split2](https://user-images.githubusercontent.com/102408/69749209-0ca41f00-115b-11ea-971f-0b4a9c14e855.jpg)

**Comment by wrathagom** [comment] 2019-11-28 03:35
@dcalvom @dakavisa I am thinking that this should already be possible by just using Handlebars in the JSON response, is that true?

**Comment by wrathagom** [comment] 2019-11-28 03:40
@Ravenous this functionality is available on master (recently committed) and will be added to a release shortly.

**Comment by wrathagom** [comment] 2019-11-29 15:35
@dakavisa is going to try and build an example.

**Comment by dakavisa** [comment] 2019-12-02 04:08
@Ravenous , With the new quick responses for action responses functionality, you can use Webhook responses to create quick responses, I attached a simple bot example that uses a country info API to display quick responses:

<img width="1107" alt="Action-Quick-Repsonses" src="https://user-images.githubusercontent.com/53984674/69930006-d8946b00-1486-11ea-9709-a18451adbb54.png">

<img width="288" alt="Response Example" src="https://user-images.githubusercontent.com/53984674/69930013-dfbb7900-1486-11ea-81a3-302cd23e1bbb.png">

[CountriesBot.json.zip](https://github.com/samtecspg/articulate/files/3909383/CountriesBot.json.zip)

**Comment by rounakraj** [comment] 2019-12-08 18:40
@dakavisa @wrathagom Can we create buttons in action response? If yes how do we do that?

**Comment by dakavisa** [comment] 2019-12-09 03:05
@rounakraj wit the latest code in master you can set quick responses for action responses in the action response tab

**Comment by rounakraj** [comment] 2019-12-09 07:31
@dakavisa Thanks i will try in master..

**Comment by rounakraj** [comment] 2019-12-09 13:50
@dakavisa Thanks i could verify the feature on master branch. However i have few queries.
Attached my quick response and chat flow.
<img width="343" alt="Screenshot 2019-12-09 at 7 17 35 PM" src="https://user-images.githubusercontent.com/6190350/70440711-cd5dc280-1ab8-11ea-99c0-4adfe53715be.png">
<img width="960" alt="Screenshot 2019-12-09 at 7 17 28 PM" src="https://user-images.githubusercontent.com/6190350/70440712-cd5dc280-1ab8-11ea-8c8d-490e71be83a2.png">

In the above cases i am using handlebars to update the button based on slot condition. I only want to show buttons if slot value is null and not when slot value is there. How to handle the else parts to not show buttons when slot value is there. Currently it shows empty buttons.

**Comment by dakavisa** [comment] 2019-12-09 16:43
@rounakraj yeah we are aware of that issue of the blank buttons, we have a fix already and will release it soon so any blanks or handlebar errors will be ignored, so for now please ignore the blank buttons.
As for what you are trying to accomplish, I think a better way to show buttons when the slot is empty is to mark it as required, so you can ask directly to the user to fill it and enter button values for the options. You can also set a limit prompt number so your agent will ask n times for the slot value.
And finally, If you still want to check if the slot is not set, the following handlebar syntax worked for me:
{{#if (not slots.zWaveDevice.value)}} Bulb {{/if}}

**Comment by rounakraj** [comment] 2019-12-09 16:48
@dakavisa Thanks for the reply. I understand marking as required is the solution but this is a backup which I have tried since marking as required is giving issue of double response already described in https://github.com/samtecspg/articulate/issues/967. #967 
I have attached my test agent with exact reproduction in https://github.com/samtecspg/articulate/issues/967#issuecomment-562933364. Did you get a chance to look at it?

**Comment by dakavisa** [comment] 2019-12-09 16:50
@rounakraj Yeah we are already looking into the double response issue, we will get back at you when we get a resolution

**Comment by rounakraj** [comment] 2019-12-09 17:07
@dakavisa thanks

**Comment by rounakraj** [comment] 2019-12-10 14:46
@dakavisa When using the chatbot agent from Slack Channel , the click on buttons have no effect.
The data is not passed on to articulate.
It displays the button and i am able to click it but there is no event going to articulate.
Am i missing something?

**Comment by wrathagom** [comment] 2019-12-10 14:51
Please create a new issue.

**Comment by dakavisa** [comment] 2019-12-12 18:36
Closing blank buttons handlebars issue with f227dc7f315466ac4ee961e6c27d6a872c21e947

**Closed by dakavisa** 2019-12-12 18:36 UTC
Labels: question
