### ISSUE TITLE
Open chat button 

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#883] opened 2019-08-25 20:10 UTC
The patch https://github.com/samtecspg/articulate/issues/863 created a new buggy behaviour

if you open an agent, then you click on the gear at the bottom left (the chat will disapear)
then you click on articulate logo to go back to the agent/connection selection page, the chat will reopen, while this patch was supposed to solve it.

if you are working on an agent, and you go to any tab that is not the "agent:agentName" and you refresh the page, the chat will be hidden, and if you click on the articulate logo, the chat will appear.

**Comment by dakavisa** [comment] 2019-08-25 23:06
I was able to reproduce this:
"if you are working on an agent, and you go to any tab that is not the "agent:agentName" and you refresh the page, the chat will be hidden"
And fixed it with: 
5a5e9157dc4a1a4b76fc96806335a8459cbbf049

But I can't reproduce this:
"if you open an agent, then you click on the gear at the bottom left (the chat will dissapear)
**then you click on articulate logo to go back to the agent/connection selection page, the chat will reopen**"
Or this:
"... **and if you click on the articulate logo, the chat will appear.**"

I am on MacOS and tried to reproduce that with Chrome and Firefox:

App flows tried:
1-) Select Agent (chat button appear) -> Press the gear on the left (chat button disappear) -> Click Articulate Logo (chat button disappear)
2-) Select Agent (chat button appear) -> Press Dialogue or Review or Analytics (chat button still on) -> Refresh Dialogue or Review or Analytics (chat button still on) -> Click Articulate Logo (chat button disappear)
3-) Select Create Agent (chat button appear) -> Insert name and description and save (chat button still on and chat open) -> Select Dialogue or Review or Analytics (chat button still on and chat open) -> Refresh Dialogue or Review or Analytics (chat button still on) -> Click Articulate Logo (chat button disappear)

Please tell me if you see something different or I'm not reproducing correctly.

**Comment by mordebip** [comment] 2019-08-25 23:20
you can just try by being on the agent selection page, and clicking on the articulate logo, it will shot the chat element, when you click again, it will close it.

(maybe i missed something when i patched)
i will apply your last patch and make a new test

**Comment by dakavisa** [comment] 2019-08-28 22:07
Closed by aa798621876e92896fdeb516fb707264022054ca

**Closed by dakavisa** 2019-08-28 22:07 UTC
