### ISSUE TITLE
Improve Horizontally scrolling agent list

### ISSUE THREAD

**Issue by thiyaga24** [samtecspg/articulate#814] opened 2019-07-11 10:58 UTC
### Issues
> *when number of Agents exceeds 5, the UI becomes messy. Please see screenshot*
> I have 10+ agents which is not even shown in the screenshot and cant able to scroll as well. 

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Which release? **0.25**
- What operating system are you running? Windows 10 Pro
- Are you running locally or in the cloud?  Both local and Cloud
- Which browser are you using? Chrome

![image](https://user-images.githubusercontent.com/49054407/61045634-db6bc200-a3f8-11e9-9379-18a497f4d9a1.png)

**Comment by wrathagom** [comment] 2019-07-11 12:46
This looks like the expected behavior, the list scroll horizontally?

@broham89

**Comment by broham89** [comment] 2019-07-11 20:34
Yeah I assumed it should scroll horizontally but now i can see that can get messy. A possible solution is to have two tabs: **Agent + Connection**

**Comment by wrathagom** [comment] 2019-07-12 22:40
How about just some sort of an arrow/indicator that it can scroll? I don't think tabs on every page is a good look.

**Comment by broham89** [comment] 2019-07-17 21:39
![agent list page v 2](https://user-images.githubusercontent.com/11262149/61413547-68a78e80-a8b1-11e9-9175-15c89512ebe3.png)

**Comment by dcalvom** [comment] 2019-08-22 18:07
Closed by https://github.com/samtecspg/articulate/commit/4a6f5d67fdbb5413c00ee948a357d5fe2d4b51a2

**Closed by dcalvom** 2019-08-22 18:07 UTC
Labels: enhancement, ui
