### ISSUE TITLE
Docker Setting not Changing

### ISSUE THREAD

**Issue by sanyaade-machine-learning** [samtecspg/articulate#271] opened 2018-07-01 09:43 UTC
Hello Everybody, Please I need help on Articulate. Many thanks in advance.

### Issues
> *I modified the docker ports settings inside docker-compose.yml 
since I am running on a server with static IP and I have original 
ports setting already in use.*

Please describe the issue you are having here and answer the question below.

- Did you download a release or pull from Master? Download the latest release from Github
 Which release? ==>  Articulate 0.11.0
- What operating system are you running? ==> Ubuntu 16.04 Server
- Are you running locally or in the cloud? ==> Locally on a Server
- Which browser are you using?==> Google Chrome

----
I modified the docker-compose.yml at the root and also those Dockerfile inside sub-folders, then run **docker-compose up**  command but to my surprise, it still tries to run on those default settings. Looks like there is overriding somewhere I cannot find.

> compose output
sanyaade@ns1:~/Applications/virtual-assistant/articulate$ clear

sanyaade@ns1:~/Applications/virtual-assistant/articulate$ ls
api				CODE_OF_CONDUCT.md  docker-compose.yml	duckling	   LICENSE	  NOTICE.md   rasa	 ui
build-compose-override.yml.bck	development.md	    docs		ISSUE_TEMPLATE.md  local-storage  package.sh  README.md
sanyaade@ns1:~/Applications/virtual-assistant/articulate$ docker-compose up
Recreating articulate_redis_1
Recreating articulate_ui_1
Recreating articulate_api_1
Recreating articulate_rasa_1
Recreating articulate_duckling_1
Attaching to articulate_api_1, articulate_redis_1, articulate_ui_1, articulate_duckling_1, articulate_rasa_1
redis_1     | 1:C 01 Jul 09:40:28.119 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1     | 1:C 01 Jul 09:40:28.148 # Redis version=4.0.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1     | 1:C 01 Jul 09:40:28.148 # Configuration loaded
redis_1     | 1:M 01 Jul 09:40:28.187 * Running mode=standalone, port=6379.
redis_1     | 1:M 01 Jul 09:40:28.187 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1     | 1:M 01 Jul 09:40:28.187 # Server initialized
redis_1     | 1:M 01 Jul 09:40:28.187 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1     | 1:M 01 Jul 09:40:28.187 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1     | 1:M 01 Jul 09:40:28.296 * DB loaded from append only file: 0.109 seconds
redis_1     | 1:M 01 Jul 09:40:28.296 * Ready to accept connections
ui_1        | yarn run v1.7.0
ui_1        | $ cross-env NODE_ENV=development node server
ui_1        | Server started ! ✓
ui_1        | 
ui_1        | Access URLs:
ui_1        | -----------------------------------
ui_1        | Localhost: http://localhost:3000
ui_1        |       LAN: http://172.19.0.4:3000
ui_1        | -----------------------------------
ui_1        | Press CTRL-C to stop
ui_1        |     
rasa_1      | 2018-07-01 09:40:31+0000 [-] Log opened.
rasa_1      | 2018-07-01 09:40:31+0000 [-] Site starting on 5000
rasa_1      | 2018-07-01 09:40:31+0000 [-] Starting factory <twisted.web.server.Site instance at 0x7f2d36f9aa28>
api_1       | Server running.
duckling_1  | no port specified, defaulting to port 8000
duckling_1  | Listening on http://0.0.0.0:8000
ui_1        | webpack built 6b7120dc0f68444d8193 in 27325ms

Please see my docke-compose.yml below:

> 
version: '3.0'

services:
  api:
    image: samtecspg/articulate-api:0.11.0
    ports: ['0.0.0.0:7500:7500']
    networks: ['alpha-nlu-network']
    entrypoint: ['node', 'start.js']
    environment:
     - SWAGGER_BASE_PATH
  ui:
    image: samtecspg/articulate-ui:0.11.0
    ports: ['0.0.0.0:3070:3070']
    networks: ['alpha-nlu-network']
    environment:
     - API_URL
  rasa:
    image: samtecspg/articulate-rasa:0.11.0
    ports: ['0.0.0.0:5070:5070']
    volumes: ["${MODEL_DIR:-./local-storage/rasa/nlu-model}:/app/projects", "${RASA_CONFIG:-./local-storage/rasa/rasa-config.yml}:/app/config.yml", "./local-storage/rasa/logs:/app/logs"]
    networks: ['alpha-nlu-network']
  duckling:
    image: samtecspg/duckling:0.1.6.0
    ports: ['0.0.0.0:8570:8570']
    networks: ['alpha-nlu-network']
  redis:
    image: redis:4.0.6-alpine
    ports: ['0.0.0.0:6579:6579']
    networks: ['alpha-nlu-network']
    command: redis-server --appendonly yes
    volumes:
      - ${REDIS_DATA:-./local-storage/redis-data}:/data

networks: {alpha-nlu-network: {}}

Please tell me what I ma doing wrong. Many thanks for your support.
Hear from you soon!

God blesses!!!

Best regards
Sanyaade

**Comment by milutz** [comment] 2018-07-01 13:41
Hi Sanyaade!

Sorry if this wasn't clear in our documentation, but the way that you change ports is you only change the the FIRST number (see https://docs.docker.com/compose/compose-file/#short-syntax-1 ) - by changing the second number you were disconnecting the port from the application that runs in the container.

So for example, to change the external port on the UI you would change the block to look like:
```
  ui:
    image: samtecspg/articulate-ui:0.11.0
    ports: ['0.0.0.0:3070:3000']
    networks: ['alpha-nlu-network']
    environment:
     - API_URL
```
The above would make the external port 3070, while leaving the application port (what is internally used by us in articulate/docker and isn't/doesn't effect port usage on your machine) at 3000

Let me know if that gets you working.

All the best!

**Comment by sanyaade-machine-learning** [comment] 2018-07-01 17:14
Hi milutz  :+1:  

Many thanks for you quick reply. I know realised my mistakes plus I was expecting the Articulate start-up screen to display the host ports but seeing only its internal ports information also got thrown off edge.

Everything works as expected. Many thanks!

My next step is to study Articulate as I will need to use it with Rasa and possible snips and other NLU kits. I came to Articulate as I have been having hell of time with training Rasa. Rasa_NLU and rasa_core whenever I issued the following command: 

> python -m rasa_nlu.train  --config sample_configs/config_spacy.yml  --data data/examples/rasa/demo-rasa.json   --path projects

I always get the error:-  Illegal instruction (core dumped)
The above error message is not helpful and difficult to trace/debug. I have posted on Gitter but no help. I have been on it for over 2 weeks (try rasa_nlu, rasa_core, starter-pack) on python 2.7.12 and also python 3.6.0 but I could not get past the training stage. Poor me!

Many thanks again for your support. 
I saw where you mentioned non-docker installation for articulate. I am going to try it as I am trying to move away from Dockerised Application. It hides a lot from you and you cannot learn how things work or study the code. Also too many image containers and many layers filling up my server storage.

Once again, many thanks!

God blesses!!!

Best regards,
Sanyaade

**Comment by milutz** [comment] 2018-07-01 19:32
Sanyaade, 

I’m going to close this issue since it sounds like the title of the issue is resolved.  Your welcome to continue posting on here and I’ll keep answering as best I can (our gitter is also a great place to post questions)

You packed a whole bunch of question/comments above I’ll try and at least touch on all of them here:

> I will need to use it with Rasa ....

Articulate is based on Rasa_NLU = Articulate will run the rasa training when you click on the train button.

> `- illegal instruction (core dumped)`

Yes, that style of python error is a pain in the butt. My guess is that is a library/requirement mis-match or an architecture issue (arm code on intel or the reverse) - or perhaps a mix of both.

Avoiding libraries issues is a big part of why we are offering docker based releases - it lets us “bake-in” the libraries in a known way, so we can avoid that type of issue

> I saw where you mentioned a non-docker installation

There isn’t anything magical about our docker installs, the parts certainly can be installed natively, but your chances of running into some craziness with libraries/install greatly increase.

The `Dockerfile` and `docker-compose.yml` files in this project (and the projects referenced) are the steps that are needed to install natively.  Definitely doable, but not fun to do (and particulately not fun to upgrade with new releases)

> ... I am trying to move away from Dockerised Application. It hides a lot from you and you cannot learn how things work or study code

It’s true that docker can make it a bit more involved to dig through a project, but I disagree that it hides or prevents the study of anything.

All docker is doing (at least in the articulate case) is making a bunch of lightweight Linux VMs (containers) that the different parts of articulate run in.

When the system is running you can jump into any of the containers with `docker exec -it [containerid] bash` (containerid is found by using `docker ps`) and look around and poke at things however you want. (Type ctrl-d or `exit` exit back to your shell - entering and exiting the container with `exec` won’t effect the container (unless you changed something))

In exchange for this extra abstraction each container gets to have precisely the libraries/versions that particular sub-application wants - with zero worry about them conflicting with each other.

Hope that helps, all the best

**Closed by milutz** 2018-07-01 19:32 UTC

**Comment by sanyaade-machine-learning** [comment] 2018-07-01 20:44
@milutz 

Thank you so much for all your efforts and support and for those explanation, pointers and guides.

Much appreciated!

I will focus on Articulate more now.

Please close the issue

God blesses!!!

Best regards,
Sanyaade
