### ISSUE TITLE
Occasionally socket erro

### ISSUE THREAD

**Issue by dcalvom** [samtecspg/articulate#398] opened 2018-11-26 21:58 UTC
I'm having this error from time to time:

`client.js:5 Uncaught TypeError: c is not a function`

**Comment by wrathagom** [comment] 2018-11-27 00:12
@malave can you try to re-produce.

**Comment by malave** [comment] 2018-11-29 14:04
@dcalvom : I can't reproduce this error, could you provide more info on the setup when you had it?

**Comment by wrathagom** [comment] 2018-12-06 02:46
Closing until we see it again.

**Closed by wrathagom** 2018-12-06 02:46 UTC
Labels: new-ui
