### ISSUE TITLE
Deleting active fallback action can cause a 500 server error

### ISSUE THREAD

**Issue by nickopris** [samtecspg/articulate#747] opened 2019-05-14 15:16 UTC
When querying the chatbot with anything that it was not trained with I get this response and not the DefaultAction:
`{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}`

Any queries with trained data triggers the appropriate action.

Creating another DefaultAction and replacing the initial one seems to work but I wonder why this happens and if this is possible to happen to any other Actions already configured.

- Did you download a release or pull from Master? Which release?
Release v0.22.0
- What operating system are you running?
Mac OSx
- Are you running locally or in the cloud?
Locally with Docker
- Which browser are you using?
Chrome - same response using Postman

**Comment by wrathagom** [comment] 2019-05-14 15:35
I'll work on reproducing. Does your fallback action have a webhook of any sorts?

**Comment by nickopris** [comment] 2019-05-14 15:42
I remember playing with some webhooks but right now the original DefaultAction is no longer visible and I did not delete it myself. The new Default Action does not use any webhooks - I can try adding one to see if I can break it.

**Comment by wrathagom** [comment] 2019-05-14 15:43
can you export your current agent? and provide that.

**Comment by nickopris** [comment] 2019-05-14 15:46
Sure, attached.
[TATA (1).json.txt](https://github.com/samtecspg/articulate/files/3178670/TATA.1.json.txt)

**Comment by dcalvom** [comment] 2019-05-14 17:25
@nickopris aren't you having this error?

```
Error: Action(s) 'Expense report access' has only 1 training example! Minimum is 2. Please fix this before training the agent.. 😨
```

**Comment by dcalvom** [comment] 2019-05-14 17:29
After I added another saying example for `Expenses report access` action I was able to train the agent and get the fallback action

![image](https://user-images.githubusercontent.com/7228045/57718796-7899bc80-763b-11e9-9f07-5d0e23e1f76b.png)

**Comment by nickopris** [comment] 2019-05-14 17:46
> @nickopris aren't you having this error?
> 
> ```
> Error: Action(s) 'Expense report access' has only 1 training example! Minimum is 2. Please fix this before training the agent.. 😨
> ```

I was getting that but added an extra example and moved past that issue. The reported error showed up once I tested with a trained set.

**Comment by dcalvom** [comment] 2019-05-14 18:16
Would you mind to import this into your cloud instance?

I think this would fix both issues that you currently have. The only change I added to this one was a change in the name to allow it to be imported, as duplicated names are blocked.

My guess is that some relation was broken, I don't know why. I already tested with the release that you are using and everything is working fine.

Import only accepts `.json` so please remove the `.txt` extension.

[TATA Test.json.txt](https://github.com/samtecspg/articulate/files/3179187/TATA.Test.json.txt)

**Comment by nickopris** [comment] 2019-05-14 18:53
Your file is working fine. I can't explain what happened. Possibly related to this - the agent I had cannot be edited (it happened also before uploading your file) 
![rasa-anomalies](https://user-images.githubusercontent.com/794552/57724046-db15ab80-7681-11e9-811f-eac098a7c4c7.gif)

**Comment by wrathagom** [comment] 2019-05-15 13:39
@dcalvom I can reproduce his error if I delete the fallback action. it will let me delete it since it isn't linked to any sayings. Once it's deleted I can chat with the agent fine so long as there are good parse results, but then as soon as something triggers the fallback action it throws the 500 error.

We should either:

- not let people delete the active fallback action
- handle the case where the fallback action needs a system fallback

**Comment by dcalvom** [comment] 2019-05-21 03:08
Closed by https://github.com/samtecspg/articulate/commit/888accc3f9c61a0bad632cbb0bdb9bba60a08fd8

**Closed by dcalvom** 2019-05-21 03:08 UTC
Labels: api, bug, ui
