### ISSUE TITLE
multiple responses given on conversation

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#837] opened 2019-07-26 13:14 UTC
### Issues
Similar to the last release, it seems that there are still problems with garbled responses.

So for 27.0 it seems slots are working properly, however there are still garbled responses/multiple

![image](https://user-images.githubusercontent.com/42249324/61953894-8944a800-af85-11e9-8685-63b023183331.png)

No errors

Source for response:

```
[
  {
    "docId": "udFoLmwBa2vB5GT3-rOC",
    "category": "default",
    "project": "pizzabot-0.27",
    "model": "default_8807d5af-375a-6bb4-d97d-91c7d39d6d58",
    "keywords": [
      {
        "start": 0,
        "end": 3,
        "value": {
          "value": "ham"
        },
        "confidence": 0.7974831999444281,
        "extractor": "ner_crf",
        "keyword": "toppings",
        "category": "default"
      },
      {
        "start": 8,
        "end": 17,
        "value": {
          "value": "pepperoni"
        },
        "confidence": 0.7414720876548766,
        "extractor": "ner_crf",
        "keyword": "toppings",
        "category": "default"
      }
    ],
    "action": {
      "name": "get order",
      "confidence": 0.5767453908920288
    },
    "action_ranking": [
      {
        "name": "get order",
        "confidence": 0.5767453908920288
      },
      {
        "name": "Goodbye",
        "confidence": 0.48416537046432495
      },
      {
        "name": "cancel order",
        "confidence": 0.46528175473213196
      },
      {
        "name": "Gratitude",
        "confidence": 0.2436220645904541
      },
      {
        "name": "Are you there",
        "confidence": 0.12403929233551025
      },
      {
        "name": "I like you",
        "confidence": 0.11463785171508789
      },
      {
        "name": "You're Welcome",
        "confidence": 0.03741035610437393
      },
      {
        "name": "Answer Mood",
        "confidence": 0.01980343461036682
      },
      {
        "name": "Who Am I",
        "confidence": 0
      },
      {
        "name": "order status",
        "confidence": 0
      }
    ],
    "elapsed_time_ms": 126,
    "categoryScore": 0.9156073331832886
  },
  {
    "docId": "udFoLmwBa2vB5GT3-rOC",
    "category": "pizzabot-0.27_modifiers",
    "project": "pizzabot-0.27",
    "model": "pizzabot-0.27_modifiers",
    "keywords": [],
    "action": {
      "name": "",
      "confidence": 0
    },
    "action_ranking": [],
    "elapsed_time_ms": 119,
    "categoryScore": 0
  }
]
```

As for this new feature: 
• Multiple messages - on platforms that support it messages will be split rather than concatenated
For small talk category it is responding correctly, but with the get order action, it is not. 

- Did you download a release or pull from Master? Which release?
release 27.0
- What operating system are you running?
10 pro
- Are you running locally or in the cloud?
local
- Which browser are you using?
FF

**Comment by wrathagom** [comment] 2019-07-31 12:16
Please re-test for 0.27.2

**Comment by wrathagom** [comment] 2019-07-31 12:17
just to point out that ham and pineapple was recognized as an actual action not a modifier. So I think this put it in the queue twice. @dcalvom

**Comment by RakibulAsheeque** [comment] 2019-08-09 06:45
I have tried it for 0.27.2. this issue still exists.

- Did you download a release or pull from Master? Which release?
release 0.27.2
- What operating system are you running?
Debian Linux 9
- Are you running locally or in the cloud?
Cloud
- Which browser are you using?
Chrome

**Comment by wrathagom** [comment] 2019-08-11 15:06
@RussellSPG was this a duplicate of the issue we discussed and closed the other day?

**Comment by RussellSPG** [comment] 2019-08-11 23:37
not sure, this is what I found when spoting for the issue of grabled responses.

**Closed** 2019-08-13 13:40 UTC
