### ISSUE TITLE
BUG: Sometimes words do not highlight in sayings New UI

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#464] opened 2019-01-09 18:34 UTC
I've found that sometimes when highlighting words to match to keywords, nothing appears and you have to repeat. Seems like sometimes an extra space has to be highlighted for the keyword box to appear.

**Comment by wrathagom** [comment] 2019-01-09 18:52
do you have error messages? A video? Anything? You're not giving enough information for this to be reproduced.

**Comment by RussellSPG** [comment] 2019-01-10 04:53
I'm sorry, it seems the problem was that I didn't have the mouse completely over the word when letting go, so it cancels the highlighting. But when doing it normally its easy to make that mistake, or not realize your not keeping the cursor on the words. 

[highlighting keywords.zip](https://github.com/samtecspg/articulate/files/2743640/highlighting.keywords.zip)

**Comment by dcalvom** [comment] 2019-01-18 00:01
There wasn't a real error, this seems to be more UX. I will close this one @wrathagom

**Closed by dcalvom** 2019-01-18 00:01 UTC
