### ISSUE TITLE
Math Handlebars

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#319] opened 2018-09-14 10:44 UTC
- Did you download a release or pull from Master? Which release?
   Working form release - v0.11.2
- What operating system are you running?
    Windows 10
- Are you running locally or in the cloud?
    Locally
- Which browser are you using?
    Firefox / Chrome
------------------------------------------------------------------------------------------------------
Hi guys. I ran into a small lock-up. Would any of you know the reason of this happening ? 
I attach a screenshot for deeper explanation.

![articulate_sum_question](https://user-images.githubusercontent.com/40358189/45545584-9e539500-b812-11e8-94ed-ec4ffae20be8.PNG)

So I found a sum handlebar in here (https://github.com/helpers/handlebars-helpers#math) that I wanted to test. But for some reason it gives me 0 as an answer where the answer should be 15 (Looking at provided example). Am I doing something wrong ? 
And BTW how would i be able to pass more than one values using Text Prompt. So in order to get sum of dynamic values so the user can input those.

Bot: "Specify numbers to sum up"
User: "1,2,3,4"
Bot: "The sum of numbers provided is = 10"

I tried that but I'm still getting 0 and not sure how to pass multiple values rather than just one.

Thanks for your time guys ! 
Bart

**Comment by wrathagom** [comment] 2018-09-14 12:09
looking at your screenshot it looks like when you copy/pasted the quotes didn’t come through quite right. Make sure the array is “[1,2,3,4,5]” as opposed to "[1,2,3,4,5]” notice the small difference in the quotes.

**Comment by wrathagom** [comment] 2018-09-14 12:10
If that doesn’t work I’ll try to reproduce the problem.

**Comment by wrathagom** [comment] 2018-09-14 12:18
never mind it is just broken :/ I'll try to poke at this today, but it's possible that it is an error in the underlying repo and we'll have to open an issue there for them to resolve it.

**Comment by wrathagom** [comment] 2018-09-14 12:36
interestingly enough `{{sum 1 2 3 4 5}} works just fine.

**Comment by bkurowski** [comment] 2018-09-14 12:43
I seems to work fine, thanks ! 
Could you please specify on how would you add or sum (doesn't matter which) numbers specified by user using Text Prompt, as I can not figure out how to read two numbers from text prompt rather than just one single value.
Example : 

User: Add Values
Bot: Specify values to add (Text Prompt)
User: Add 2 + 3
Bot: Addition answer is = 5

As i can not find anything on that in supplied docs. 
Thank you.

**Comment by wrathagom** [comment] 2018-09-14 12:47
For addition and sum it's easy if we can assume all numbers in the utterance need to be added together. `What is the sum of 1, 2, 3, 4, 5` Create a slot filled by sys.duckling_number and make sure it is a list. Then the handlebars to sum all values in that slot would be {{sum slots.Number.value}} where `slots.Number.value` returns an array since the slot is marked as a list.

Here's what it looks like when working for me:
![image](https://user-images.githubusercontent.com/1779894/45551065-c1724a80-b7fa-11e8-8876-e10f50ebcdb5.png)

**Comment by wrathagom** [comment] 2018-09-14 12:51
Can work with written out numbers as well
![image](https://user-images.githubusercontent.com/1779894/45551287-65f48c80-b7fb-11e8-811a-6547e9c8c567.png)

**Comment by bkurowski** [comment] 2018-09-14 13:31
Thank you  !! U are great helper ! 
Best Regards !

**Comment by wrathagom** [comment] 2018-09-14 15:42
thanks for the high praise. We're happy to have you as part of our community.

**Closed by wrathagom** 2018-09-14 15:42 UTC
