### ISSUE TITLE
Help video for Settings is unavailable

### ISSUE THREAD

**Issue by sabatale** [samtecspg/articulate#1008] opened 2020-04-11 17:11 UTC
### Issues
The Help button for Settings redirects to a video that is not available to users ([https://youtu.be/o807YDeK6Vg](https://youtu.be/o807YDeK6Vg)).

EDIT: Same for /users.

EDIT2: The video for "Connections" is the same as Agents.

**Comment by wrathagom** [comment] 2020-04-12 01:34
Duplicate of #702

**Closed by wrathagom** 2020-04-12 01:34 UTC
