### ISSUE TITLE
Assigning entities for intents problem

### ISSUE THREAD

**Issue by bkurowski** [samtecspg/articulate#376] opened 2018-11-21 12:40 UTC
### Issues
Please describe the issue you are having here and answer the question below.

----
Hi Guys ! So i have encountered a weird let me call it a bug. 
As when writing "User Says" and applying different entities to the sentence i encountered this type of reaction, see below.

![capture](https://user-images.githubusercontent.com/40358189/48841427-4fcdf400-ed89-11e8-8b44-1a70367a89de.PNG)

When you look at word "Also" this was not selected at all for example, it was word onion that was selected. I was careful and did not attach any empty spaces with the words.
And when I wanted to mark onion as an entity, it hovered word "also" but as well it mixed up the rest of them too. As you can see words "take away" , "all" & "quarter pounder" these are either selected wrong or non sense. 
Have you ever encountered this reaction ? 

PS: I have tried re-completing the task 2/3 times and it is the same reaction every time.

Thank you.
Kind Regards.

- Did you download a release or pull from Master? Which release?
--> v0.12.3
- What operating system are you running?
--> Ubuntu
- Are you running locally or in the cloud?
--> Locally
- Which browser are you using?
--> Chrome

----

**Comment by wrathagom** [comment] 2018-11-22 02:14
What was originally highlighted?

**Comment by bkurowski** [comment] 2018-11-22 10:07
The red markings on the screenshot indicate the wrong word that got changed "It self".
The black markings are the correct ones that should be selected and was at the start. 

![capture](https://user-images.githubusercontent.com/40358189/48895943-45b9fd00-ee3e-11e8-9a4c-ca37e47df956.PNG)

Until i assigned entity for cheese or onion, it mixed all the other entities.

Did you have such reactions before ?

**Comment by wrathagom** [comment] 2018-11-22 15:47
Yeah, we have seen this before. And likely won't be fixed until our new UI is rolled out. The problem is that cheese is a part of cheeseburger. So when it tries to re-highlight cheese and find it in the sentence it highlights starting at the wrong place and throws everything else off.

@dcalvom is your fix for the new UI something that can be ported back to current versions?

**Comment by bkurowski** [comment] 2018-11-22 15:50
Oh I see. That is OK, i will definitely wait for the new UI  👍 
No worries I will remember for now to watch out for words so these will not get mixed up.
That's what I was actually thinking but I preferred to ask an expert.
Thanks bud  !

**Closed** 2018-11-27 00:44 UTC
