### ISSUE TITLE
New Session Button on web demo page does not work.

### ISSUE THREAD

**Issue by rounakraj** [samtecspg/articulate#973] opened 2019-12-19 12:50 UTC
I am using master branch.
On the web demo URL the New session button does not create a session.

<img width="296" alt="Screenshot 2019-12-19 at 6 19 07 PM" src="https://user-images.githubusercontent.com/6190350/71174883-364cf380-228c-11ea-82bb-353e8535e407.png">

**Comment by wrathagom** [comment] 2019-12-19 13:04
So what happens when you click it?

**Comment by rounakraj** [comment] 2019-12-19 13:33
Nothing Happens. The icon does not change. no new session is created.

**Comment by wrathagom** [comment] 2019-12-19 13:34
And the current conversation stays in the chat panel?

**Comment by rounakraj** [comment] 2019-12-19 13:58
The current conversation is cleared, but the moment some else types anything in their session it appears in this window also.

**Comment by wrathagom** [comment] 2019-12-19 14:03
Closed as a duplicate of #972

**Closed by wrathagom** 2019-12-19 14:03 UTC
