### ISSUE TITLE
elasticsearch: access denied

### ISSUE THREAD

**Issue by dohoangminhquan** [samtecspg/articulate#994] opened 2020-03-05 16:19 UTC
I pulled articulate-v0.31.1 and used docker-compose to run on ubuntu 16.04. As the result, I got the following error:

api_1            | 2020/03/05 16:08:25 Problem with request: Get http://elasticsearch:9200: dial tcp 172.18.0.2:9200: connect: connection refused. Sleeping 1s
duckling_1       | no port specified, defaulting to port 8000
duckling_1       | Listening on http://0.0.0.0:8000
elasticsearch_1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
ui_1             | Server started ! ✓
ui_1             | 
ui_1             | Access URLs:
ui_1             | -----------------------------------
ui_1             | Localhost: http://localhost:3000
ui_1             |       LAN: http://172.18.0.4:3000
ui_1             | -----------------------------------
ui_1             | Press CTRL-C to stop
ui_1             |     
api_1            | 2020/03/05 16:08:26 Problem with request: Get http://elasticsearch:9200: dial tcp 172.18.0.2:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/03/05 16:08:27 Problem with request: Get http://elasticsearch:9200: dial tcp 172.18.0.2:9200: connect: connection refused. Sleeping 1s
rasa_1           | 2020-03-05 16:08:28+0000 [-] Log opened.
rasa_1           | 2020-03-05 16:08:28+0000 [-] Site starting on 5000
rasa_1           | 2020-03-05 16:08:28+0000 [-] Starting factory <twisted.web.server.Site object at 0x7fd2df74da20>
api_1            | 2020/03/05 16:08:28 Problem with request: Get http://elasticsearch:9200: dial tcp 172.18.0.2:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/03/05 16:08:29 Problem with request: Get http://elasticsearch:9200: dial tcp 172.18.0.2:9200: connect: connection refused. Sleeping 1s
api_1            | 2020/03/05 16:08:30 Problem with request: Get http://elasticsearch:9200: dial tcp 172.18.0.2:9200: connect: connection refused. Sleeping 1s
elasticsearch_1  | {"type": "server", "timestamp": "2020-03-05T16:08:31,112+0000", "level": "WARN", "component": "o.e.b.ElasticsearchUncaughtExceptionHandler", "cluster.name": "docker-cluster", "node.name": "153f879b7a3c",  "message": "uncaught exception in thread [main]" , 
elasticsearch_1  | "stacktrace": ["org.elasticsearch.bootstrap.StartupException: ElasticsearchException[failed to bind service]; nested: AccessDeniedException[/usr/share/elasticsearch/data/nodes];",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:115) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "Caused by: org.elasticsearch.ElasticsearchException: failed to bind service",
elasticsearch_1  | "at org.elasticsearch.node.Node.<init>(Node.java:582) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:211) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:211) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:325) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "... 6 more",
elasticsearch_1  | "Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes",
elasticsearch_1  | "at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]",
elasticsearch_1  | "at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]",
elasticsearch_1  | "at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]",
elasticsearch_1  | "at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]",
elasticsearch_1  | "at java.nio.file.Files.createDirectory(Files.java:692) ~[?:?]",
elasticsearch_1  | "at java.nio.file.Files.createAndCheckIsDirectory(Files.java:799) ~[?:?]",
elasticsearch_1  | "at java.nio.file.Files.createDirectories(Files.java:785) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:270) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:207) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:267) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.node.Node.<init>(Node.java:272) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:211) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:211) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:325) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.1.1.jar:7.1.1]",
elasticsearch_1  | "... 6 more"] }
articulate-v0311_elasticsearch_1 exited with code 1

Does anyone know how to fix it?

thanks
----

**Comment by wrathagom** [comment] 2020-03-05 16:31
Duplicate of #659 see the solution there.

https://github.com/samtecspg/articulate/issues/659#issuecomment-485026159

**Closed by wrathagom** 2020-03-05 16:31 UTC
